### ISSUE TITLE
Diagrama de sequência

### ISSUE THREAD

**Issue by arthurarp** [UnBArqDsw/2020.1_G6_Pomo#12]
## Descrição

Criar o diagrama de sequência do projeto

## Tarefas
- [ ] Fazer o diagrama
- [ ] Documentar

## Critérios de aceitação

- [ ] O diagrama deve estar na notação UML.

## Como isso vai beneficiar o projeto?

Diminuir a complexidade de entendimento do projeto

**Comment by markinlimac** [comment]
Esse diagrama está sendo feito?
