### ISSUE TITLE
Diagrama de atividades

### ISSUE THREAD

**Issue by arthurarp** [UnBArqDsw/2020.1_G6_Pomo#13]
## Descrição

Criar o diagrama de atividades do projeto

## Tarefas
- [x] Fazer o diagrama
- [x] Documentar

## Critérios de aceitação

- [x] O diagrama deve estar na notação UML.

## Como isso vai beneficiar o projeto?

Diminuir a complexidade de entendimento do projeto

**Comment by flyerjohn** [comment]
Doc “mergeado” sem inconsistências, boa @Andre-Eduardo!
