### ISSUE TITLE
Diagrama de estados

### ISSUE THREAD

**Issue by arthurarp** [UnBArqDsw/2020.1_G6_Pomo#14]
## Descrição

Criar o diagrama de estados do projeto

## Tarefas
- [x] Fazer o diagrama
- [x] Documentar

## Critérios de aceitação

- [x] O diagrama deve estar na notação UML.

## Como isso vai beneficiar o projeto?

Diminuir a complexidade de entendimento do projeto

**Comment by flyerjohn** [comment]
Vi la que o @markinlimac commitou a documentação
