### ISSUE TITLE
Criar documento de arquitetura

### ISSUE THREAD

**Issue by arthurarp** [UnBArqDsw/2020.1_G6_Pomo#15]
## Descrição

Apresentar a primeira versão da arquitetura do projeto POMO
## Tarefas
- [x] Introdução
- [x] Representação da arquitetura
- [x] Conclusão 

## Critérios de aceitação

- [x] Todos os membros devem estar cientes do modelo arquitetural
- [x] Estar de acordo com o projeto

## Como isso vai beneficiar o projeto?

Fornecer uma visão geral sobre a arquitetura do projeto.

**Comment by arthurarp** [comment]
Hoje foi feito pela equipe o diagrama da primeira versão da arquitetura

**Comment by markinlimac** [comment]
Como está nosso documento de arquitetura?

**Comment by flyerjohn** [comment]
O @Andre-Eduardo fechou as pendencias!
