### ISSUE TITLE
Notação BPMN da metodologia

### ISSUE THREAD

**Issue by arthurarp** [UnBArqDsw/2020.1_G6_Pomo#16]
## Descrição

Criar o diagrama BPMN da metodologia utilizada.

## Tarefas
- [x] Fazer o diagrama
- [x] Documentar
- [x] Anexar pequeno áudio explicando a metodologia.

## Critérios de aceitação

- [x] Deve estar de acordo com a metodologia apresentada [aqui](https://unbarqdsw.github.io/2020.1_G6_Pomo/base/modulo1.2/metodologia/).

## Como isso vai beneficiar o projeto?

Auxiliar no entendimento do método de desenvolvimento utilizado pela equipe.

**Comment by arthurarp** [comment]
Acabei de subir o diagrama, só falta subir o áudio explicando.

**Comment by flyerjohn** [comment]
Boaa! Eu dei uma olhada e achei que ficou ótimo.
