### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by arthurarp** [UnBArqDsw/2020.1_G6_Pomo#17]
**Descrição da nova feature:**

Construir o protótipo de alta fidelidade.

**Tarefas**  

* [x] Cada membro assinado apresentar um protótipo de baixa fidelidade
* [x] Construção do protótipo em grupo

**Critérios de aceitação**
  

* [x] O protótipo de alta fidelidade deve juntar o que há de melhor nos protótipos individuais.
* [x] Todos do grupo devem estar de acordo com o protótipo
* [x] Protótipo feito no adobe XD
* [x] O protótipo deve estar dinâmico
* [x] Fazer a documentação do protótipo

**Como isso vai beneficiar o projeto?**

Facilitar o desenvolvimento. O protótipo deve estar pronto para o frontend começar a ser desenvolvido.

**Comment by arthurarp** [comment]
Adicionei o conceito de prototipo de baixa fidelidade la galera, quando fizerem o individual só subir la. Também criei uma pasta la na pasta das imagens pra colocar os arquivos

**Comment by flyerjohn** [comment]
Ok, vou adicionar o meu lá!!

**Comment by flyerjohn** [comment]
O @markinlimac já finalizou os retoques do protótipo de alta fidelidade, essa issue pode ser fechada após o doc for adicionado.
