### ISSUE TITLE
Criar CRUD UserCrontoller

### ISSUE THREAD

**Issue by markinlimac** [UnBArqDsw/2020.1_G6_Pomo#22]
**Descrição da nova feature:**
Criar código da controller que irá fazer gestão de usuários 

**Tarefas**  

* [x] Criar código em node.js

**Critérios de aceitação**
  

* [x] O código deve estar no repositório https://github.com/UnBArqDsw/2020.1_G6_Pomo_Backend 
* [x] O código deve seguir a documentação
* [x] Qualquer alteração que não condiz com a documentação, deve gerar uma atualização na documentação
* [x] O código deve possuir o método público *create()*
* [x] O código deve possuir o método público *update()*

**Como isso vai beneficiar o projeto?**

Começar o desenvolvimento do backend do projeto

**Comment by thallysbraz** [comment]
Os métodos read e delete não precisa ser implementados, visto que, nunca deve deletar um usuário da base de dados, então não precisa do delete e não precisa do método de read, pois o Sequelize (ORM utilizado para manipular o banco de dados) ja tem esse método integrado, ou seja, não precisa criar de novo.
O método reset_password por necessitar de diversas etapas, fica melhor estruturado se for criado como service ou como um Controller separado de usuário. Portanto, necessário criar uma nova issue para essa Feature

**Comment by markinlimac** [comment]
Beleza @thallysbraz, irei criar uma nova issue para a feature da senha e retirar os métodos desnecessários do critério de aceitação!

**Comment by markinlimac** [comment]
Com isso a issue ja está pronta para ser fechada?

**Comment by thallysbraz** [comment]
Sim, pode ser fechada

**Comment by markinlimac** [comment]
Beleza, aceitei o seu PR, irei fechar a issue
