### ISSUE TITLE
Criar CRUD ChatCrontoller

### ISSUE THREAD

**Issue by markinlimac** [UnBArqDsw/2020.1_G6_Pomo#23]
**Descrição da nova feature:**
Criar código da controller que irá fazer gestão do chat

**Tarefas**  

* [ ] Criar código em node.js

**Critérios de aceitação**
  

* [ ] O código deve estar no repositório https://github.com/UnBArqDsw/2020.1_G6_Pomo_Backend 
* [ ] O código deve seguir a documentação
* [ ] Qualquer alteração que não condiz com a documentação, deve gerar uma atualização na documentação
* [ ] O código deve possuir o método público *create()*
* [ ] O código deve possuir o método público *read()*
* [ ] O código deve possuir o método público *update()*
* [ ] O código deve possuir o método público *delete()*

**Como isso vai beneficiar o projeto?**

Começar o desenvolvimento do backend do projeto

**Comment by flyerjohn** [comment]
Ficou massa, @Andre-Eduardo! 🚀
