### ISSUE TITLE
Criar CRUD NotificationsCrontoller

### ISSUE THREAD

**Issue by markinlimac** [UnBArqDsw/2020.1_G6_Pomo#24]
**Descrição da nova feature:**
Criar código da controller que irá fazer gestão de notificações

**Tarefas**  

* [x] Criar código em node.js

**Critérios de aceitação**
  

* [x] O código deve estar no repositório https://github.com/UnBArqDsw/2020.1_G6_Pomo_Backend 
* [x] O código deve seguir a documentação
* [x] Qualquer alteração que não condiz com a documentação, deve gerar uma atualização na documentação
* [x] O código deve possuir o método público *read()*
* [x] O código deve possuir o método público *update()*
* [x] O código deve possuir o método público *delete()*

**Como isso vai beneficiar o projeto?**

Começar o desenvolvimento do backend do projeto

**Comment by flyerjohn** [comment]
Chequei o seu PR la @markinlimac, ficou safe! 🚀
