### ISSUE TITLE
Criar CRUD TimerCrontoller

### ISSUE THREAD

**Issue by markinlimac** [UnBArqDsw/2020.1_G6_Pomo#26]
**Descrição da nova feature:**
Criar código da controller que irá fazer gestão do timer

**Tarefas**  

* [x] Criar código em node.js

**Critérios de aceitação**
  

* [x] O código deve estar no repositório https://github.com/UnBArqDsw/2020.1_G6_Pomo_Backend 
* [x] O código deve seguir a documentação
* [x] Qualquer alteração que não condiz com a documentação, deve gerar uma atualização na documentação
* [x] O código deve possuir o atributo privado *startDate*
* [x] O código deve possuir o atributo privado *endDate*
* [x] O código deve possuir o atributo privado *currentDate*
* [x] O código deve possuir os métodos públicos *getters*
* [x] O código deve possuir os métodos públicos *setters*

**Como isso vai beneficiar o projeto?**

Começar o desenvolvimento do backend do projeto

**Comment by flyerjohn** [comment]
CRUD criado, so uma duvida, eu acredito que esses métodos descritos de start, reset, pause, notifyUser, playSound, etc, devem ser realizados no front. Gostaria de esclarecimento.

**Comment by markinlimac** [comment]
Fala @flyerjohn, a issue foi criada seguindo o que esta descrito na documentação. Concordo que não faz sentido esses métodos estarem no back, irei abrir issue de correção da documentação e assim que o PR dessa issue for aceito, fecharei ela

**Comment by flyerjohn** [comment]
PR já realizado!
