### ISSUE TITLE
Formar ambiente de desenvolvimento da frontend

### ISSUE THREAD

**Issue by flyerjohn** [UnBArqDsw/2020.1_G6_Pomo#4]
## Titulo da Issue
Formar ambiente de desenvolvimento
## Descrição

Tarefa imprescindível para o início da implementação da aplicação
## Tarefas
- [x] Criar o novo repositório para frontend
- [x] Adicionar docker
- [x] Criar readme contextualizada
 
## Critérios de aceitação

- [x] Ambiente de desenvolvimento completo
- [x] Readme preenchida

## Como isso vai beneficiar o projeto?
Isso terá um impacto direto no fluxo de desenvolvimento do projeto, sendo assim completamente necessário e urgente.

**Comment by markinlimac** [comment]
A tag arquitetura deveria ser mudada para devops

**Comment by flyerjohn** [comment]
Corrigido! Obrigado pelo headsup 😄

**Comment by flyerjohn** [comment]
O ambiente de desenvolvimento já está dockerizado e pronto para progressão! 🥳
