### ISSUE TITLE
Refatorar Documento de Arquitetura

### ISSUE THREAD

**Issue by Andre-Eduardo** [UnBArqDsw/2020.1_G6_Pomo#49]
**Descrição da nova feature:**

Essa versao da documentação deve incluir os tópicos de ficar de acordo com o modelo proposto pela disciplina 
**Tarefas**  

* [x] Incluir tópico Definições, Acrônimos e Abreviações
* [x] Incluir tópico Restrições e Metas Arquiteturais
* [x] Incluir tópico Visão Lógica
* [x] Incluir tópico Diagrama de Pacotes Geral
* [x] Incluir tópico Diagrama de Classes do Back-end API
* [x] Incluir tópico Visualização de implantação
* [x] Incluir tópico Visão de Implementação
* [x] Incluir tópico Tamanho e Desempenho
* [x] Incluir tópico Qualidade

**Critérios de aceitação**
  

* [x] O documento deve incluir todos os tópicos listados.

**Como isso vai beneficiar o projeto?**

Melhorar a documentação de Arquitetura do Pomo

**Comment by markinlimac** [comment]
Documento de arquitetura finalizado!
