### ISSUE TITLE
Formação do ambiente de desenvolvimento backend

### ISSUE THREAD

**Issue by flyerjohn** [UnBArqDsw/2020.1_G6_Pomo#5]
## Titulo da Issue
Formação do ambiente de desenvolvimento backend
## Descrição

Tarefa imprescindível para o início da implementação da aplicação.
## Tarefas
- [x] Criar repositório para backend
- [x] Adicionar estrutura inicial de arquivos do nodejs
- [x] Adicionar docker
- [x] Criar readme contextualizado

## Critérios de aceitação

- [x] Ambiente de desenvolvimento completo.
- [x] Readme preenchida 
## Como isso vai beneficiar o projeto?
Isso terá um impacto direto no fluxo de desenvolvimento do projeto, sendo assim completamente necessário e urgente.

**Comment by flyerjohn** [comment]
Preciso de ajuda na _conteinerização_ do repo..

**Comment by arthurarp** [comment]
Bora @flyerjohn. Só dizer o dia

**Comment by markinlimac** [comment]
Posso ajudar também

**Comment by flyerjohn** [comment]
Ambiente quase pronto. Agora só falta adicionar as dependências de bancos.
