### ISSUE TITLE
Adaptar aplicação para iOS nativo

### ISSUE THREAD

**Issue by flyerjohn** [UnBArqDsw/2020.1_G6_Pomo#52]
**Descrição da nova feature:**
Essa issue delega a necessidade de adaptação das telas do aplicativo para código Swift nativo.

**Tarefas**  

* [x] Adicionar Tab Bar conforme protótipo de alta fidelidade
* [x] Adicionar [Tela 1](https://unbarqdsw.github.io/2020.1_G6_Pomo/extra/prototipos/alta_fidelidade/) conforme protótipo de alta fidelidade
* [x] Adicionar [Tela 2](https://unbarqdsw.github.io/2020.1_G6_Pomo/extra/prototipos/alta_fidelidade/) conforme protótipo de alta fidelidade
* [x] Adicionar [Tela 3](https://unbarqdsw.github.io/2020.1_G6_Pomo/extra/prototipos/alta_fidelidade/) conforme protótipo de alta fidelidade
* [x] Adicionar [Tela 4](https://unbarqdsw.github.io/2020.1_G6_Pomo/extra/prototipos/alta_fidelidade/) conforme protótipo de alta fidelidade
* [x] Adicionar [Tela 5](https://unbarqdsw.github.io/2020.1_G6_Pomo/extra/prototipos/alta_fidelidade/) conforme protótipo de alta fidelidade
* [x] Adicionar [Tela 6](https://unbarqdsw.github.io/2020.1_G6_Pomo/extra/prototipos/alta_fidelidade/) conforme protótipo de alta fidelidade
* [x] Adicionar [Tela 7](https://unbarqdsw.github.io/2020.1_G6_Pomo/extra/prototipos/alta_fidelidade/) conforme protótipo de alta fidelidade
* [x] Adicionar [Telas Contextuais](https://unbarqdsw.github.io/2020.1_G6_Pomo/extra/prototipos/alta_fidelidade/) conforme protótipo de alta fidelidade
**Critérios de aceitação**
  

* [x] As telas devem estar em conformidade com o protótipo, à medida do possível  
* [x] A aplicação deverá rodar para qualquer um que siga as instruções presentes no README do [repositório iOS](https://github.com/UnBArqDsw/2020.1_G6_Pomo_iOS)

**Como isso vai beneficiar o projeto?**
Isso tornará a decisão do grupo de tornar a aplicação mais nativa o possível para os dois maiores sistemas operacionais moveis disponíveis, com enfoque no iOS mais recente, iOS 14.2.

**Comment by flyerjohn** [comment]
Adicionada completamente a tela de sessões de foco e incompletamente a tela do timer.

**Comment by arthurarp** [comment]
Bom trabalho, João! Ficou realmente muito boa a tela de sessões. Vi pelo vídeo de demonstração que você enviou

**Comment by flyerjohn** [comment]
Tela 3 adicionada conforme o protótipo de alta fidelidade!

**Comment by flyerjohn** [comment]
Aplicação adaptada completamente. Agora faltam alguns ajustes em algumas telas, criarei logo mais as issues para esses.
