### ISSUE TITLE
Diagrama de classes

### ISSUE THREAD

**Issue by arthurarp** [UnBArqDsw/2020.1_G6_Pomo#7]
## Descrição

Criar o diagrama de classes do projeto

## Tarefas
- [x] Fazer o diagrama
- [x] Documentar

## Critérios de aceitação

- [x] O diagrama deve estar na notação UML.

## Como isso vai beneficiar o projeto?

Diminuir a complexidade de entendimento do projeto

**Comment by arthurarp** [comment]
Bora fazer isso. Que dia fica melhor pra vcs?

**Comment by flyerjohn** [comment]
Eu estarei disponível em quase todos os dias, menos dia 09/09 das 10h às 1130h

**Comment by flyerjohn** [comment]
Fechamos esse!
