### ISSUE TITLE
Diagrama de componentes

### ISSUE THREAD

**Issue by arthurarp** [UnBArqDsw/2020.1_G6_Pomo#8]
## Descrição

Criar o diagrama de componentes do projeto

## Tarefas
- [x] Fazer o diagrama
- [x] Documentar

## Critérios de aceitação

- [x] O diagrama deve estar na notação UML.

## Como isso vai beneficiar o projeto?

Diminuir a complexidade de entendimento do projeto

**Comment by flyerjohn** [comment]
Diagrama finalizado sem grandes problemas. Aguardo verificação para fechar issue.

**Comment by arthurarp** [comment]
O diagrama está de acordo com o projeto, consegui entender bem. Muito bom trabalho, @flyerjohn!
